spring:
  application:
    name: produtos

  datasource:
    url: jdbc:mysql://localhost:3306/revisao-produtos
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect